name: docker build and push

on:
  workflow_call:
    inputs:
      container-name:
        required: true
        type: string

jobs:
  build-and-push:
    steps:
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build and push
        run: docker build --platform linux/arm64 -t dkilchytskyi/${{ inputs.container-name }} --push .
      - name: ping n8n redeploy webhook
        run: curl --location --request POST 'https://n8n.cloudstats.org/webhook/edfc8a0a-8f05-48ce-8736-999a94104075?containerName=${{ inputs.container-name }}' --header ${{ secrets.N8N_REDEPLOY_WEBHOOK_AUTH_HEADER }}